name: Python Web Deploy

on: [push]

jobs:
 
  build:
    runs-on: ubuntu-latest
    env:
      JOBS_ENV: ../../

    steps: 
      - name: Get maven-github-actions repo
        uses: actions/checkout@v2
        with:
          ref: feature/DTPP-34

      - name: test location where I am maven-github-actions
        run: ls -l maven/
              
      - name: Get pipeline-github-actions
        uses: actions/checkout@v2
        with:
          repository: openprojectsad/pipeline-github-actions
          ref: feature/DTPP-34
          token: ${{ secrets.PAT_TOKEN }}

      - name: test location where I am pipeline-github-actions
        run: ls -l ${JOBS_ENV}

